# -*- coding: utf-8 -*-
"""streamlit app new code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ebtwE7TgwMebRq-FcYgL0oHSOuJDyarM
"""

import streamlit as st
import joblib
import numpy as np
import pandas as pd

# ----------------------
# Load Pre-trained Model
# ----------------------
@st.cache_resource
def load_model():
    model = joblib.load("logistic_regression_model.pkl")  # Change to your model filename
    scaler = joblib.load("scaler.pkl")  # Change to your scaler filename
    return model, scaler

model, scaler = load_model()

# ----------------------
# App Title
# ----------------------
st.title("Hyperglycaemia Severity Prediction")
st.write("This app predicts the severity of hyperglycaemia based on patient health data.")

# ----------------------
# User Input Form
# ----------------------
with st.form("input_form"):
    age = st.number_input("Age", min_value=1, max_value=120, value=45)
    bmi = st.number_input("BMI", min_value=10.0, max_value=60.0, value=25.0)
    glucose = st.number_input("Current Glucose Level (mg/dL)", min_value=40, max_value=500, value=110)
    insulin_dose = st.number_input("Insulin Dose (units)", min_value=0.0, max_value=100.0, value=10.0)
    carbs = st.number_input("Carbohydrate Intake (grams)", min_value=0, max_value=300, value=50)
    activity = st.number_input("Physical Activity (minutes)", min_value=0, max_value=300, value=30)
    stress = st.slider("Stress Level (1 = Low, 10 = High)", min_value=1, max_value=10, value=5)
    hba1c = st.number_input("HbA1c (%)", min_value=4.0, max_value=15.0, value=6.5)

    submitted = st.form_submit_button("Predict")

# ----------------------
# Make Prediction
# ----------------------
if submitted:
    # Arrange features into same order as during training
    input_data = np.array([[glucose, insulin_dose, carbs, activity, stress, age, bmi, hba1c]])

    # Scale features
    input_data_scaled = scaler.transform(input_data)

    # Predict
    prediction = model.predict(input_data_scaled)[0]
    probabilities = model.predict_proba(input_data_scaled)[0]

    # Mapping prediction index to class name
    class_labels = ["Hypoglycemia", "Normal", "Mild Hyperglycemia", "Moderate Hyperglycemia", "Severe Hyperglycemia"]

    st.subheader(f"Predicted Severity: **{class_labels[prediction]}**")
    st.write("### Probability Scores:")
    prob_df = pd.DataFrame([probabilities], columns=class_labels)
    st.dataframe(prob_df.style.format("{:.2%}"))

    # Recommendations
    recommendations = {
        "Hypoglycemia": "Monitor glucose, consume quick carbs, and consult your healthcare provider.",
        "Normal": "Maintain your current lifestyle and monitoring routine.",
        "Mild Hyperglycemia": "Review your diet and activity; consider discussing adjustments with your doctor.",
        "Moderate Hyperglycemia": "Monitor frequently and consult your healthcare team for medication or lifestyle adjustments.",
        "Severe Hyperglycemia": "Seek medical attention immediately."
    }
    st.info(recommendations[class_labels[prediction]])